apiVersion: v1
kind: Service
metadata:
  name: inspector-canary
  labels:
    app: inspector
    track: canary
spec:
  type: NodePort
  selector:
    app: inspector
    track: canary
  ports:
  - name: http
    nodePort: 36001
    port: 80
    protocol: TCP
